# Generated by Django 4.2.20 on 2025-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('asset_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=10, verbose_name='자산 종류')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'asset_type'], name='golds_price_date_7b8d61_idx')],
            },
        ),
    ]
